create table if not exists public.cms_editor_revisions (
  id bigint generated by default as identity primary key,
  document_key text not null,
  html text not null,
  css text not null default '',
  mode text not null default 'original-site',
  site_css_href text,
  rendered_html text not null,
  saved_by text not null default 'cms-admin',
  created_at timestamp with time zone not null default now(),
  constraint cms_editor_revisions_document_key_check check (btrim(document_key) <> '')
);

create index if not exists cms_editor_revisions_document_created_idx
  on public.cms_editor_revisions (document_key, created_at desc);

create table if not exists public.cms_editor_current (
  document_key text primary key,
  html text not null,
  css text not null default '',
  mode text not null default 'original-site',
  site_css_href text,
  rendered_html text not null,
  last_revision_id bigint references public.cms_editor_revisions (id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint cms_editor_current_document_key_check check (btrim(document_key) <> '')
);

alter table public.cms_editor_revisions enable row level security;
alter table public.cms_editor_current enable row level security;

revoke all on table public.cms_editor_revisions from public, anon, authenticated;
revoke all on table public.cms_editor_current from public, anon, authenticated;
revoke all on sequence public.cms_editor_revisions_id_seq from public, anon, authenticated;

grant select, insert, update, delete on table public.cms_editor_revisions to service_role;
grant select, insert, update, delete on table public.cms_editor_current to service_role;
grant usage, select on sequence public.cms_editor_revisions_id_seq to service_role;

comment on table public.cms_editor_revisions is
  'Immutable history of each explicit /cms/editor save.';
comment on table public.cms_editor_current is
  'Current /cms/editor landing state used by the CMS preview and SFTP publishing flow.';
comment on column public.cms_editor_current.rendered_html is
  'Full HTML document generated from the GrapesJS html/css and sent to SFTP during publishing.';

insert into storage.buckets (id, name, public)
values ('cms', 'cms', false)
on conflict (id) do update
set public = excluded.public;
